### ISSUE TITLE
打开钱包后报错

### ISSUE THREAD

**Issue by wyh136** [AntShares/AntShares#11]
![1](https://cloud.githubusercontent.com/assets/12386613/17476120/edae10f0-5d90-11e6-9cde-45f4ca0fd872.png)

**Comment by wyh136** [comment]
error.log：
An error occurred while updating the entries. See the inner exception for details.
   在 Microsoft.Data.Entity.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   在 Microsoft.Data.Entity.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   在 Microsoft.Data.Entity.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   在 Microsoft.Data.Entity.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   在 AntShares.Implementations.Wallets.EntityFramework.UserWallet.OnProcessNewBlock(Block block, IEnumerable`1 transactions, IEnumerable`1 added, IEnumerable`1 changed, IEnumerable`1 deleted) 位置 C:\Users\Erik\Documents\Visual Studio 2015\Projects\AntShares\AntSharesCore\Implementations\Wallets\EntityFramework\UserWallet.cs:行号 317
   在 AntShares.Wallets.Wallet.ProcessNewBlock(Block block) 位置 C:\Users\Erik\Documents\Visual Studio 2015\Projects\AntShares\AntSharesCore\Wallets\Wallet.cs:行号 614
   在 AntShares.Wallets.Wallet.ProcessBlocks() 位置 C:\Users\Erik\Documents\Visual Studio 2015\Projects\AntShares\AntSharesCore\Wallets\Wallet.cs:行号 541
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Threading.ThreadHelper.ThreadStart()

**Comment by erikzhang** [comment]
This bug has been fixed in commit [6d9f810](https://github.com/AntShares/AntShares/commit/6d9f810bd90179a9394689101134e41498d64dba)
