### ISSUE TITLE
Some window and menu display Chinese, when I run the client in English systme

### ISSUE THREAD

**Issue by chenzhitong** [AntShares/AntShares#15]
Some window and menu display Chinese, when I run the client in English systme

![2cea812c5f1b4b0a8f96fa0671ad477d](https://cloud.githubusercontent.com/assets/6295602/19374757/dcc6e4ac-9200-11e6-9204-98a28e846369.jpg)

![27ca7bae4d369b7ec1e45bc675de2e8d](https://cloud.githubusercontent.com/assets/6295602/19374764/e7a5ba4c-9200-11e6-9a35-e193c79fb862.jpg)

![78c8a9f1d489697e25cf134d773d02cf](https://cloud.githubusercontent.com/assets/6295602/19374768/ed124df6-9200-11e6-9775-d9d55b76049a.jpg)

![e60df2f9a9d6998b438f756e27d3e73b](https://cloud.githubusercontent.com/assets/6295602/19374772/f4cf81da-9200-11e6-8c41-5c507b949a94.jpg)

**Comment by erikzhang** [comment]
Fixed in commit [872f75381075cc04aa5e6081f3a2ce087a6e7650](https://github.com/AntShares/AntShares/commit/872f75381075cc04aa5e6081f3a2ce087a6e7650)
