### ISSUE TITLE
小蚁客户端领取小蚁币程序奔溃，再次运行打开钱包数据库就崩溃。。。

### ISSUE THREAD

**Issue by wnf0000** [AntShares/AntShares#17]
领取小蚁币时点一次全部领取按钮，弹出来一个窗口，里边一个文本框显示交易编号还是什么来着，我关闭窗口后，再点一次全部领取，然后程序就崩溃了。
崩溃后我重新运行程序，能正常运行，在打开钱包数据库操作时，选择钱包文件，输入密码，点确定，这时候程序再崩溃，再怎么重复都是这样崩溃。。。
以下是错误窗口的日志
`See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.FormatException: One of the identified items was in an invalid format.
   at AntShares.Core.ClaimTransaction.DeserializeExclusiveData(BinaryReader reader) in C:\Users\Erik\Documents\Visual Studio 2015\Projects\AntShares\AntSharesCore\Core\ClaimTransaction.cs:line 34
   at AntShares.Core.Transaction.DeserializeUnsignedWithoutType(BinaryReader reader) in C:\Users\Erik\Documents\Visual Studio 2015\Projects\AntShares\AntSharesCore\Core\Transaction.cs:line 170
   at AntShares.Core.Transaction.DeserializeFrom(BinaryReader reader) in C:\Users\Erik\Documents\Visual Studio 2015\Projects\AntShares\AntSharesCore\Core\Transaction.cs:line 154
   at AntShares.Core.Transaction.DeserializeFrom(Byte[] value, Int32 offset) in C:\Users\Erik\Documents\Visual Studio 2015\Projects\AntShares\AntSharesCore\Core\Transaction.cs:line 138
   at AntShares.Implementations.Wallets.EntityFramework.UserWallet.<>c.<GetTransactionInfo>b__15_0(Transaction p) in C:\Users\Erik\Documents\Visual Studio 2015\Projects\AntShares\AntSharesCore\Implementations\Wallets\EntityFramework\UserWallet.cs:line 130
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at AntShares.UI.MainForm.CurrentWallet_TransactionsChanged(Object sender, IEnumerable`1 transactions) in C:\Users\Erik\Documents\Visual Studio 2015\Projects\AntShares\AntSharesUI\UI\MainForm.cs:line 95
   at AntShares.UI.MainForm.ChangeWallet(UserWallet wallet) in C:\Users\Erik\Documents\Visual Studio 2015\Projects\AntShares\AntSharesUI\UI\MainForm.cs:line 60
   at AntShares.UI.MainForm.打开钱包数据库OToolStripMenuItem_Click(Object sender, EventArgs e) in C:\Users\Erik\Documents\Visual Studio 2015\Projects\AntShares\AntSharesUI\UI\MainForm.cs:line 305
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.2001.0 built by: NETFXREL1
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
AntSharesUI
    Assembly Version: 1.0.6134.21697
    Win32 Version: 1.0.6134.21697
    CodeBase: file:///C:/%E8%99%9A%E6%8B%9F%E5%B8%81/AntShares/AntSharesUI.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.2001.0 built by: NETFXREL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.2001.0 built by: NETFXREL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.2001.0 built by: NETFXREL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
AntSharesCore
    Assembly Version: 1.0.6134.21696
    Win32 Version: 1.0.6134.21696
    CodeBase: file:///C:/%E8%99%9A%E6%8B%9F%E5%B8%81/AntShares/AntSharesCore.DLL
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.2001.0 built by: NETFXREL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.2001.0 built by: NETFXREL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.2001.0 built by: NETFXREL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
AntSharesUI.resources
    Assembly Version: 1.0.6134.21697
    Win32 Version: 1.0.6134.21697
    CodeBase: file:///C:/%E8%99%9A%E6%8B%9F%E5%B8%81/AntShares/zh-Hans/AntSharesUI.resources.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.2001.0 built by: NETFXREL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.2001.0 built by: NETFXREL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.2001.0 built by: NETFXREL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
EntityFramework.Core
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.0.11116
    CodeBase: file:///C:/%E8%99%9A%E6%8B%9F%E5%B8%81/AntShares/EntityFramework.Core.DLL
----------------------------------------
System.Interactive.Async
    Assembly Version: 1.2.0.0
    Win32 Version: 1.2.50730
    CodeBase: file:///C:/%E8%99%9A%E6%8B%9F%E5%B8%81/AntShares/System.Interactive.Async.DLL
----------------------------------------
Microsoft.Extensions.DependencyInjection.Abstractions
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.11116
    CodeBase: file:///C:/%E8%99%9A%E6%8B%9F%E5%B8%81/AntShares/Microsoft.Extensions.DependencyInjection.Abstractions.DLL
----------------------------------------
Microsoft.Extensions.DependencyInjection
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.11116
    CodeBase: file:///C:/%E8%99%9A%E6%8B%9F%E5%B8%81/AntShares/Microsoft.Extensions.DependencyInjection.DLL
----------------------------------------
Microsoft.Extensions.OptionsModel
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.11116
    CodeBase: file:///C:/%E8%99%9A%E6%8B%9F%E5%B8%81/AntShares/Microsoft.Extensions.OptionsModel.DLL
----------------------------------------
Microsoft.Extensions.Logging
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.11116
    CodeBase: file:///C:/%E8%99%9A%E6%8B%9F%E5%B8%81/AntShares/Microsoft.Extensions.Logging.DLL
----------------------------------------
Microsoft.Extensions.Caching.Abstractions
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.11116
    CodeBase: file:///C:/%E8%99%9A%E6%8B%9F%E5%B8%81/AntShares/Microsoft.Extensions.Caching.Abstractions.DLL
----------------------------------------
Microsoft.Extensions.Caching.Memory
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.11116
    CodeBase: file:///C:/%E8%99%9A%E6%8B%9F%E5%B8%81/AntShares/Microsoft.Extensions.Caching.Memory.DLL
----------------------------------------
Remotion.Linq
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.1.0
    CodeBase: file:///C:/%E8%99%9A%E6%8B%9F%E5%B8%81/AntShares/Remotion.Linq.DLL
----------------------------------------
System.Runtime
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.2001.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
----------------------------------------
System.Linq.Expressions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.2001.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Linq.Expressions/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Linq.Expressions.dll
----------------------------------------
Microsoft.Extensions.Logging.Abstractions
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.11116
    CodeBase: file:///C:/%E8%99%9A%E6%8B%9F%E5%B8%81/AntShares/Microsoft.Extensions.Logging.Abstractions.DLL
----------------------------------------
Microsoft.Data.Sqlite
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.11116
    CodeBase: file:///C:/%E8%99%9A%E6%8B%9F%E5%B8%81/AntShares/Microsoft.Data.Sqlite.DLL
----------------------------------------
EntityFramework.Sqlite
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.0.11116
    CodeBase: file:///C:/%E8%99%9A%E6%8B%9F%E5%B8%81/AntShares/EntityFramework.Sqlite.DLL
----------------------------------------
EntityFramework.Relational
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.0.11116
    CodeBase: file:///C:/%E8%99%9A%E6%8B%9F%E5%B8%81/AntShares/EntityFramework.Relational.DLL
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.23516.01
    CodeBase: file:///C:/%E8%99%9A%E6%8B%9F%E5%B8%81/AntShares/System.Diagnostics.DiagnosticSource.DLL
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.6.2001.0 built by: NETFXREL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
System.ComponentModel.DataAnnotations
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.2001.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.DataAnnotations/v4.0_4.0.0.0__31bf3856ad364e35/System.ComponentModel.DataAnnotations.dll
----------------------------------------
System.Threading
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.2001.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Threading/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Threading.dll
----------------------------------------
System.Diagnostics.Tracing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.2001.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Diagnostics.Tracing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Diagnostics.Tracing.dll
----------------------------------------
System.Reflection
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.2001.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Reflection/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Reflection.dll
----------------------------------------
System.Collections
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.2001.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Collections/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Collections.dll
----------------------------------------
System.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.2001.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Linq/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Linq.dll
----------------------------------------
System.Reflection.Extensions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.2001.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Reflection.Extensions/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Reflection.Extensions.dll
----------------------------------------
System.Linq.Queryable
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.2001.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Linq.Queryable/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Linq.Queryable.dll
----------------------------------------
System.Runtime.Extensions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.2001.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Extensions/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.Extensions.dll
----------------------------------------
Microsoft.Extensions.Primitives
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.11116
    CodeBase: file:///C:/%E8%99%9A%E6%8B%9F%E5%B8%81/AntShares/Microsoft.Extensions.Primitives.DLL
----------------------------------------
System.ObjectModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.2001.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ObjectModel/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.ObjectModel.dll
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.2001.0 built by: NETFXREL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
System.EnterpriseServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.2001.0 built by: NETFXREL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
Microsoft.Extensions.PlatformAbstractions
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.11116
    CodeBase: file:///C:/%E8%99%9A%E6%8B%9F%E5%B8%81/AntShares/Microsoft.Extensions.PlatformAbstractions.DLL
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.2001.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.2001.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
System.Security
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.2001.0 built by: NETFXREL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

`

**Comment by erikzhang** [comment]
fixed in commit [d08bb9461501e5c3ccfa11d3f5bbc10aca434bf3](https://github.com/AntShares/AntShares/commit/d08bb9461501e5c3ccfa11d3f5bbc10aca434bf3)
