### ISSUE TITLE
TestNet Request Page Broken

### ISSUE THREAD

**Issue by Ejhfast** [AntShares/AntShares#24]
A few of us have been trying to get TestNet funds through: https://www.antshares.org/Testnet/Create

Unfortunately, the form rejects public keys generated by MainNet wallets. Is there another way to generate public keys that work on the TestNet? If not, perhaps there is a bug?

Specifically, the error message we are getting is (in English) "Incorrect little ant public key"

(Apologies if this is not the correct place to post this error, wasn't sure where else to do it.)

**Comment by Ejhfast** [comment]
Closed as it seems that people were pasting their address in the form instead of their public key.

**Comment by hipstersmoothie** [comment]
Do you know where you can find the public key? I can't seem to get it. On a mac
