### ISSUE TITLE
RPC: getrawmempool error

### ISSUE THREAD

**Issue by AlexChien** [AntShares/AntShares#8]
similar issue as #7 

```
curl -d '{"jsonrpc":"2.0","id":"1","method":"getrawmempool","params":[]}' http://127.0.0.1:20332
{"jsonrpc":"2.0","id":"1","error":{"code":-32601,"message":"Method not found","data":"   at AntShares.Network.RPC.RpcServer.InternalCall(String method, JArray _params)\n   at AntShares.Network.RPC.RpcServer.ProcessRequest(JObject request)"}}
```

**Comment by erikzhang** [comment]
The published version of peer does not support this command "getrawmempool".
If you need to use it, you have to build the latest version [master](https://github.com/AntShares/AntShares/tree/master) on windows or [coreclr](https://github.com/AntShares/AntShares/tree/coreclr) on linux.
