### ISSUE TITLE
RPC: getblock <index>

### ISSUE THREAD

**Issue by AlexChien** [AntShares/AntShares#9]
```
curl -d '{"jsonrpc":"2.0","id":"1","method":"getblock","params":[222]}' http://127.0.0.1:20332
{"jsonrpc":"2.0","id":"1","error":{"code":-2146233033,"message":"\u5B57\u7B26\u4E32\u0022333\u0022\u65E0\u6CD5\u8BC6\u522B\u4E3A\u6B63\u786E\u7684UInt256\u3002","data":"   at AntShares.UInt256.Parse(String s)\n   at AntShares.Network.RPC.RpcServer.InternalCall(String method, JArray _params)\n   at AntShares.Network.RPC.RpcServer.ProcessRequest(JObject request)"}}
```

The error says "字符串"333"无法识别为正确的UInt256。".  `getblock` is supposed to support block hash or height as parameter.

**Comment by erikzhang** [comment]
The published version of peer does not support this command "getblock <index>".
If you need to use it, you have to build the latest version [master](https://github.com/AntShares/AntShares/tree/master) on windows or [coreclr](https://github.com/AntShares/AntShares/tree/coreclr) on linux.
